from MDAnalysis.tests.datafiles import PDB_small
import os

import umbrellas
from umbrellas.reaction import Distance

def test_new_ensemble(tmpdir):
    cpath = tmpdir.join('config.ini')
    rpath = tmpdir.join('replicas.db')
    
    e = umbrellas.Ensemble(config_path=str(cpath))
    assert e
    assert os.path.exists(str(cpath))
    assert os.path.exists(str(rpath))
    
def test_add_replica(tmpdir):
    cpath = tmpdir.join('config.ini')
    rpath = tmpdir.join('replicas.db')

    e = umbrellas.Ensemble(config_path=str(cpath))
    
    e.add_replica(name='testpdb', path=PDB_small)
    r = e.get_replica('testpdb')
    assert r
    assert rpath.read() == """# Replica DB
# AUTOGENERATED - EDIT AT YOUR OWN RISK

[replicas]
    [[testpdb]]
        path = /Library/Frameworks/Python.framework/Versions/2.6/lib/python2.6/site-packages/MDAnalysis-0.7.2_devel-py2.6-macosx-10.3-fat.egg/MDAnalysis/tests/data/adk_open.pdb

"""

